### ISSUE TITLE
Test SELECT retrieval speed optimizations

### ISSUE THREAD

**Issue by kauberry** [pacifica/pacifica-metadata#101]
### Pacifica Core Software versions
[Versions of the pacifica core software components related to this issue]

### Platform Details
[Operating system distribution and release version. Cloud provider if running in the cloud]

### Scenario:
Lots of extra queries are getting run during the WHERE select and to_hash creation process

### Actual Result:
Optimize data retrieval to use the pre-existing foreignkey id values from the main query

**Comment by dmlb2000** [comment]
This should be closed now...
