### ISSUE TITLE
failed to parse error when uploading large file with arbitrary tags

### ISSUE THREAD

**Issue by czebotar** [pacifica/pacifica-metadata#15]
### Pacifica Metadata version
master

### Pacifica Core Software versions
master

### Platform Details
dev

### Scenario:
Upload large file test, included arbitrary tags

### Steps to Reproduce:
fallocate 3g file
upload

### Expected Result:
File uploaded and accessible by status tool

### Actual Result:
"transaction pending" from the uploader page never ended, status page did not show file as avaiable.  File did reach ingester and was moved to the backend storage.  See attached stack dump and metadata files.
[stack_dump.txt](https://github.com/pacifica/pacifica-metadata/files/947779/stack_dump.txt)
[metadata.txt](https://github.com/pacifica/pacifica-metadata/files/947780/metadata.txt)

**Comment by dmlb2000** [comment]
This is a good bug with the limitations of the automatic mapping of the file size in elasticsearch. We'll have to fix this.

**Comment by dmlb2000** [comment]
You may be able to upload the data you requested by splitting up the single large file into smaller ones... say 10x 500Mb files instead of 1x 10Gb file for example

**Comment by dmlb2000** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/current/number.html

Seems like integer is 32bit integer we need to evaluate the rest of the mapping see if 64bit integer is required for other parts of the model.
