### ISSUE TITLE
[Improvement] Standardize use of user versus person

### ISSUE THREAD

**Issue by GitBytes** [pacifica/pacifica-metadata#238]
### Pacifica Metadata version
`>= v0.10.0`

There are a number of locations throughout the data model and tables that use a combination of "person" or "user". We should standardize on a singular canonical key for this type of object.

See https://github.com/pacifica/pacifica-metadata/blob/master/pacifica/metadata/orm/user_group.py#L20 for an example of this.

**Comment by dmlb2000** [comment]
The change from person as the attribute to user should have been done a while ago, I must have missed this one.
