### ISSUE TITLE
Filter out "soft" deleted entries?

### ISSUE THREAD

**Issue by kauberry** [pacifica/pacifica-metadata#273]
### Pacifica Metadata version
0.12.3.1

### Pacifica Core Software versions
1.0

### Scenario:
I need to be able to retrieve entries from the rest API, but want to exclude anything that has been "soft deleted" (deleted column is not null). When pulling info for the EUS sync script, I would like to be able to just see things that aren't deleted.

### Steps to Reproduce:
I can't see any way to filter out soft deleted records from the REST endpoint

**Comment by dmlb2000** [comment]
I think this was the intent from the beginning for the deleted flag to be a filter of sorts. I'm thinking it should be fine to include this. The only tool that might be affected is the Metadata Management UI tool.
