### ISSUE TITLE
Add more flexible mapping types to Elasticsearch

### ISSUE THREAD

**Issue by kauberry** [pacifica/pacifica-metadata#60]
### Scenario:
Now that we've switched to ES 5.5, the mappings for certain text data types need to be set such that both the analyzed and non-analyzed versions are indexed and stored

### Steps to Reproduce:
Fields that only have the 'keyword' type are not indexed for search using each individual word in the string. This hinders searching.

### Expected Result:
Should be able to use analyzed text for searching and non-analyzed text (keywords) for aggregation/facet use

**Comment by dmlb2000** [comment]
This should be fixed with #59
